# Generated by Django 2.0.7 on 2018-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20180704_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
