# Generated by Django 2.0.7 on 2018-07-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20180705_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('name', 'city'), 'verbose_name': 'warehouse', 'verbose_name_plural': 'warehouses'},
        ),
    ]
