# Generated by Django 2.0.7 on 2018-07-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20180706_1444'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
