# Generated by Django 2.0.7 on 2018-07-28 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20180725_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='birthdate'),
        ),
    ]
