# Generated by Django 2.0.7 on 2018-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20180728_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.NullBooleanField(choices=[(True, 'Male'), (False, 'Female'), (None, 'Not Sure')], verbose_name='gender'),
        ),
    ]
