# Generated by Django 2.0.7 on 2018-07-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Place', '0002_auto_20180704_2216'),
        ('Warehouse', '0002_warehouse_address'),
        ('Person', '0003_auto_20180704_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(default=None, max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Place.City')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop owner+', to='Person.Person')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman', to='Person.Person')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ('name', 'city'),
            },
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.ShopType'),
        ),
        migrations.AddField(
            model_name='shop',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Warehouse.Warehouse'),
        ),
    ]
