# Generated by Django 2.0.7 on 2018-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='shop type'),
        ),
    ]
