# Generated by Django 2.0.7 on 2018-07-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20180704_2216'),
        ('person', '0005_auto_20180706_1444'),
        ('warehouse', '0005_auto_20180708_1354'),
        ('shop', '0002_auto_20180708_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='address')),
                ('website', models.URLField(blank=True, verbose_name='web site')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.City', verbose_name='city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_owner', to='person.Person', verbose_name='shop owner')),
                ('sellers', models.ManyToManyField(related_name='sellers', to='person.Person', verbose_name='sellers')),
                ('shop_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.ShopType', verbose_name='shop type')),
                ('warehouses', models.ManyToManyField(to='warehouse.Warehouse', verbose_name='warehouses')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ('name', 'city'),
            },
        ),
    ]
