# Generated by Django 2.0.7 on 2018-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20180704_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
