# Generated by Django 2.0.7 on 2018-07-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20180704_2105'),
        ('Warehouse', '0003_auto_20180704_2248'),
        ('Shop', '0003_auto_20180704_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_owner', to='Person.Person'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='salesman',
        ),
        migrations.AddField(
            model_name='shop',
            name='salesman',
            field=models.ManyToManyField(related_name='salesman', to='Person.Person'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='shop',
            name='warehouse',
            field=models.ManyToManyField(to='Warehouse.Warehouse'),
        ),
    ]
